/* Shared navigation, theme, currency, notification and confirmation functions. */
const pageLinks = [
  ['dashboard','index.html','▦','Dashboard'], ['transactions','transactions.html','⇄','Transactions'],
  ['add','add-transaction.html','＋','Add transaction'], ['categories','categories.html','◫','Categories'],
  ['reports','reports.html','◔','Reports'], ['settings','settings.html','⚙','Settings']
];
function formatMoney(value) { const s = Storage.getSettings(); return new Intl.NumberFormat('en-IN', { style: 'currency', currency: s.currency, maximumFractionDigits: 2 }).format(Number(value) || 0); }
function escapeHtml(text) { const div = document.createElement('div'); div.textContent = text || ''; return div.innerHTML; }
function showToast(message, kind = 'success') { const el = document.getElementById('toast'); if (!el) return; el.textContent = message; el.className = `toast show ${kind}`; setTimeout(() => el.className = 'toast', 2800); }
function applyTheme(theme) { document.documentElement.dataset.theme = theme; document.querySelectorAll('#themeToggle').forEach(b => b.textContent = theme === 'dark' ? '☀' : '☾'); const setting = document.getElementById('settingsTheme'); if (setting) setting.textContent = theme === 'dark' ? 'Switch to light mode' : 'Switch to dark mode'; }
function confirmAction(title, text, onConfirm) { const root = document.getElementById('modalRoot'); if (!root) return; root.innerHTML = `<div class="modal-backdrop"><div class="modal"><span class="modal-icon">!</span><h2>${title}</h2><p>${text}</p><div class="modal-actions"><button class="secondary-button" id="modalCancel">Cancel</button><button class="danger-button" id="modalConfirm">Confirm</button></div></div></div>`; document.getElementById('modalCancel').onclick = () => root.innerHTML = ''; document.getElementById('modalConfirm').onclick = () => { root.innerHTML = ''; onConfirm(); }; }
function buildSidebar() { const page = document.body.dataset.page; document.getElementById('sidebar').innerHTML = `<a class="brand" href="index.html"><span>◈</span><div>penny<pulse</p></div></a><nav>${pageLinks.map(([id, href, icon, name]) => `<a class="nav-link ${page === id ? 'active' : ''}" href="${href}"><span>${icon}</span>${name}</a>`).join('')}</nav><div class="sidebar-bottom"><span class="safe-dot"></span><div><strong>Your data is private</strong><small>Saved in this browser</small></div></div>`; }
function initApp() { buildSidebar(); const settings = Storage.getSettings(); applyTheme(settings.theme); document.querySelectorAll('#themeToggle').forEach(b => b.onclick = () => { const next = Storage.getSettings().theme === 'dark' ? 'light' : 'dark'; Storage.saveSettings({ ...Storage.getSettings(), theme: next }); applyTheme(next); window.dispatchEvent(new Event('themeChanged')); }); document.getElementById('menuButton')?.addEventListener('click', () => document.getElementById('sidebar').classList.toggle('open')); const today = document.getElementById('today'); if (today) today.textContent = new Date().toLocaleDateString('en-IN', { weekday:'short', day:'numeric', month:'short' }); initSettings(); }
function initSettings() { const select = document.getElementById('currencySelect'); if (select) { select.value = Storage.getSettings().currency; select.onchange = () => { Storage.saveSettings({ ...Storage.getSettings(), currency: select.value }); showToast('Currency updated'); }; } document.getElementById('settingsTheme')?.addEventListener('click', () => document.getElementById('themeToggle').click()); document.getElementById('clearData')?.addEventListener('click', () => confirmAction('Clear all transactions?', 'Every saved income and expense entry will be permanently removed.', () => { Storage.clear(); showToast('All transaction data cleared'); })); document.getElementById('resetApp')?.addEventListener('click', () => confirmAction('Reset application?', 'This will delete transactions and restore the default settings.', () => { localStorage.removeItem(Storage.transactionKey); localStorage.removeItem(Storage.settingsKey); applyTheme('light'); showToast('Application reset'); })); }
document.addEventListener('DOMContentLoaded', initApp);
